version: '2'

services:
  api:
    image: 'sonatype/nexus3:latest'
    container_name: 'api'
    restart: always
    expose:
- '8081'
    ports:
- '8081:8081'
    volumes:
- './nexus-data:/nexus-data'
    environment:
TZ: "Asia/Seoul"
    networks:
- devops

  proxy:
    container_name: proxy
    image: nginx:latest
    restart: always
    ports:
- "80:80"
- "443:443"
    volumes:
- ./appdata/conf.d:/etc/nginx/conf.d
- /home/ec2-user/nexus/appdata/conf:/etc/letsencrypt/live
    depends_on:
- api
    networks:
- devops

networks:
  devops:
    driver: bridge
